config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'products#index'
  resources :products do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, :cost, :country_of_origin, presence: true
  validates_length_of :name, maximum: 100
  has_many :reviews, dependent: :destroy

  scope :three_most_recent, -> { order(created_at: :desc).limit(3)}

  scope :italy, -> { where(country_of_origin: "Italy")}

  scope :most_reviewed, -> {(
    select("products.id, products.name, count(reviews.id) as reviews_count")
    .joins(:reviews)
    .group("products.id")
    .order("reviews_count DESC")
    .limit(250)
    )}
    

  before_save(:titleize_product)
  private
    def titleize_product
      self.name = self.name.titlecase
    end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  validates_length_of :content_body, minimum: 50
  validates_length_of :content_body, maximum: 250
  validates :rating, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
  validates :author, presence: true
  validates :rating, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :only => [:new, :edit] do
    redirect_to new_user_session_path unless current_user && current_user.admin
 end
 
  def index
    @products = Product.all
    @recent_products = Product.three_most_recent
    @most_reviewed_product = Product.most_reviewed
    render :index
  end

  def new
    @product = Product.new
    render :new
  end

  def create
    @product = Product.new(product_params)
    @product.user = current_user
    if @product.save
      flash[:notice] = "Product successfully added!"
      redirect_to products_path
    else
      flash[:alert] = "Unable to add product, see error"
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
    render :edit
  end

  def show
    @product = Product.find(params[:id])
    render :show
  end

  def update
    @product= Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "Product successfully updated!"
      redirect_to products_path
    else
      flash[:alert] = "Unable to update product, see error"
      render :edit
    end
  end


  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "Product successfully removed!"
    redirect_to products_path
  end

  private
    def product_params
      params.require(:product).permit(:name, :cost, :country_of_origin)
    end
 end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  skip_before_action :authenticate_user!
  
  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
    render :new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      flash[:notice] = "Review successfully added!"
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def show
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :show
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    redirect_to product_path(@product)
  end

  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      flash[:notice] = "Review successfully updated!"
      redirect_to product_path(@review.product)
    else
      flash[:alert] = "Unable to update review, see error"
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    flash[:notice] = "Review successfully removed!"
    redirect_to product_path(@review.product)
  end

  private
  def review_params
    params.require(:review).permit(:author, :content_body, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_product_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= form_for @product do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :cost %>
  <%= f.text_field :cost %>
  <%= f.label :country_of_origin %>
  <%= f.text_field :country_of_origin %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsFoodStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%= render 'shared/navbar' %>

    <%= flash[:alert] %>
    <%= flash[:notice] %>

    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render "layouts/product_form" %>

app/views/products/index.html.erb
<h1>Products</h1>

<% if current_user && current_user.admin %>
  <%= link_to "Create new product", products_path %>
<% end %>

<% if @most_reviewed_product.any?%>
<%= link_to @most_reviewed_product.first.name, product_path(@most_reviewed_product.first)%></li>
<% end %>

<% if @products.any? %>
  <ul>
    <% @products.each do |product| %>
      <li><%= link_to product.name, product_path(product) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no products yet.</p>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render "layouts/product_form" %>

app/views/products/show.html.erb
<h1>Product name:<%= @product.name %></h1>
<h3>Country of origin: <%= @product.country_of_origin %></h3>

<% if @product.reviews.any? %>
<p>Product Reviews</p>

  <ul>
    <% @product.reviews.each do |review| %>
      <li><%= review.author %> - <%= review.content_body %> |
        <%=link_to "Edit Review", edit_product_review_path(@product, review) %> |
        <%=link_to "Delete Review", product_review_path(@product, review),
          :data => {:confirm => "Are you sure?", :method => "delete"} %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No reviews yet</p>
<% end %>

<p><%= link_to "Add a new review", new_product_review_path(@product) %></p>
<p><%= link_to "Edit Product", edit_product_path(@product) %></p>
<p><%= link_to "Delete Product", product_path(@product),
                                 :data => {:confirm => "Are you sure?",
                                           :method => "delete"} %>
</p>
<p><%= link_to "Return to Product List", products_path %></p>

app/views/reviews/_review_form.html.erb
<%= render('layouts/errors', :object => @review) %>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :content_body %>
  <%= f.text_field :content_body %>
  <%= f.label :rating %>
  <%= f.text_field :rating %>
  <p><%= f.submit %></p>
<% end %>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<%= render "review_form" %>

app/views/reviews/new.html.erb
<h1>New Review <%= @product.name %></h1>

<%= render "review_form" %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Specialty Food Store</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="w-100">
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
        </li>
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to 'Register', new_user_registration_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
        </li>
        <% end %>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>